### ISSUE TITLE
SyntaxError: Non-ASCII character 

### ISSUE THREAD

**Issue by arqamawais786** [ThibaultNocchi/Python-Ant-Colony-Algorithm#1]
Hi dear,
When I execute GUI.py file, it shows following error:
File "/home/arqam/Python-Ant-Colony-Algorithm-master/Model.py", line 6
SyntaxError: Non-ASCII character '\xc3' in file /home/arqam/Python-Ant-Colony-Algorithm-master/Model.py on line 6, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by ThibaultNocchi** [comment]
Noted, I'll look into this really quick :)

**Comment by ThibaultNocchi** [comment]
For me it works, are you using Python 3?

**Comment by arqamawais786** [comment]
Yeah, I'm using Python3 and also now execute this successfully. Thanks
